[build.environment]
  YARN_VERSION = "1.22.4"
  NPM_VERSION = "6.10.3"
  HUGO_VERSION = "0.58.0"

[build]
  command = "yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build:preview"

[[redirects]]
  from = "/vote"
  to = "/post/register-to-vote-in-the-general-election/"  
